openapi: 3.0.0
info:
  version: 1.0.0
  title: BotStacks Assistant API
  description: test
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
paths:
  /assistant/{botstackId}/message:
    post:
      description: Send a message to a botstack assistant
      parameters:
        - in: header
          name: x-api-key
          schema:
            type: string
          required: true
          description: The API key
        - in: path
          name: botstackId
          schema:
            type: string
          required: true
          description: UUID of the botstack assistant
      requestBody:
        description: Hey so...
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                #apiKey:
                  #type: string
                  #description: If not in the header can be included in the body
                waitForResponse:
                  type: boolean
                  description: should the api wait for a response or return it later
                message:
                  type: string
                  description: The message to send to the assistant
                userId:
                  type: string
                  description: The current user ID. This is used to maintain a the chat conversation. If not provided, it is treated as a new conversation.

      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
